### ISSUE TITLE
Returning an Rxjs Observable rather than a promise

### ISSUE THREAD

**Issue by christianacca** [Breeze/breeze.bridge.angular#1]
Question: How can you cancel the underlying http request that `EntityManager.executeQuery` is making in such a way so that the promise `executeQuery` is returning is never resolved?

OK, that was a leading/trick question - it's not possible!

---

I think the bridge is a great step in the right direction toward angular 2 integration, but...

I think the integration is significantly limited without a change to `EntityManager`.

Without a change to `EntityManager` async methods so that the underlying Rxjs `Observerable` created by angular 2 is returned, you've **sacrificed one of the key benefits of Rxjs - that of being able to cancel the underlying http request.**

**Comment by marcelgood** [comment]
Like many existing async libraries, breeze is completely promise based at this point. Without rewriting some of its internals, we won't be able to support Observerables at this point. We have tossed around this idea, but so far haven't decided to go down that route.

**Comment by ccrowhurstram** [comment]
Understand that the change to using Observable throughout would be significant.

Of course, the problem with such a significant change is the burden of backwards compatibility. For this I would recommend a backwards compatibility shim that would turn the Observable into a promise using the `toPromise` Operator.

That way `EntityManager` could be written in terms of observables and the shim provide a simple adapter for those wanting the old promised based API.

This shim would then be given a deprecation notice after an acceptable period of time.

**Comment by marcelgood** [comment]
We would probably decide to just break from 1.x and go to 2.x with a complete rewrite. We are tossing around the idea of rewriting Breeze in TypeScript and break it up into smaller modules where possible. No timeline on this yet, though.

**Comment by ccrowhurstram** [comment]
OK.

If there's anything you think I could help out with to move this feature along, let me know. I would hope I could persuade my employer to sponsor some of my time as we're heavily invested in breeze and angular.

Thanks
Christian

**Comment by marcelgood** [comment]
Thanks for the offer. I'll keep it in mind.

**Comment by marcelgood** [comment]
BTW, we've done a number of Angular 2 projects for customers at this time and provide consulting in this area. If you need any assistance, let me know.

**Comment by ccrowhurstram** [comment]
What would be the best way to start a conversation about how you could help out on a consulting basis?
Thanks
Christian

**Comment by marcelgood** [comment]
Submit your information through the following link and I'll reach out to you directly.

https://www.ideablade.com/free-consultation

**Comment by ccrowhurstram** [comment]
OK thanks

**Comment by ccrowhurstram** [comment]
Just sent my details

**Comment by marcelgood** [comment]
Got it. I'll contact you via email to schedule something for next week.

**Comment by ccrowhurstram** [comment]
great
