### ISSUE TITLE
redux, ngrx etc. [immutable data structures] and [breeze as api service]

### ISSUE THREAD

**Issue by djleonskennedy** [Breeze/breeze.bridge.angular#12]
Hello

I started project with **angular 2** and **ngrx**, it requires to use **_immutable_** data structures.
As you know breeze js use own data engine that cannot be use in immutable way (as i know for now)

1) Do breeze have API for serialization data ? that allow me get payload and put to store? (i cannot find any example)

NOTE: i can invoke getters and get values to put it in store as JavaScript plain object. it's looks fine
however, if i need to update something it's big problem for me

For example: from my service

```
 public changePinning(typeName, item) {
     const userGuid$ = this.userState$
       .map(user => user.guid);

     return userGuid$.flatMap(guid => {
       if (item.pinned == null || item.pinned == false) {
         const newPin = this.em.createEntity("Pinning", { user_guid: guid });
         item.Pinnings.push(newPin);
       } else {
         const userPin = Enumerable
           .from(item.Pinnings)
           .where((x: any) => x.user_guid == guid)
           .toArray();
         if (userPin.length > 0) {
           const pin : any = userPin[0];
           pin.entityAspect.setDeleted();
         }
       }
       return Observable.fromPromise(<any>this.em.saveChanges()
         .then(() => ({pin: !item.pinned, guid: item.guid})))
     })
   }
```

2) Can i avoid use **item** that is **_Entity_** model to update : 

 ```
const newPin = this.em.createEntity("Pinning", { user_guid: guid });
         item.Pinnings.push(newPin);
```

and do something like:

"Hey i have guid and data to change, please change me this record and give serialized data": like
```

const newPin = this.em.createEntity("Pinning", { user_guid: guid });
const item = this.em.getItemByGuid(item.guid); /* for example */
item.Pinnings.concat(newPin); /* for example */

const newSerializedItem =  this.em.saveChanges().getSerialized() /* for example */
```
and work with JS Object

I mean can we use breeze as API Service ?

Please advice can i use **breeze** in this way?

Thank you

**Comment by marcelgood** [comment]
Breeze is a different approach from redux, ngrx and immutable data structures. We don't really believe that the redux approach is the right approach for business/CRUD applications that are essentially all about modifying data. Breeze and redux are opposite approaches to data management, so you won't find much fun in trying to use Breeze in a redux scenario. 

You might find the following podcast informative where we touch on the Breeze vs. Redux topic a little bit towards the end. Most of the podcast is about using Visual Studio to develop Angular apps, but we touch on other topics as well. Ward Bell has been giving talks on the subject as well. There are similarities to Redux in how we approach building apps with Breeze, but we fundamentally don't use immutable data structures and I wouldn't recommend trying to use Breeze in such a way. You would give up most of what Breeze has to offer. 

https://devchat.tv/adv-in-angular/113-aia-angular-2-in-a-net-world

**Comment by djleonskennedy** [comment]
@marcelgood Thank you for explanation
