### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by dsoltesz** [Breeze/breeze.bridge.angular#13]
I've updated to Angular 4 rc3 and get build errors for the breeze angular ajax adapter now.

`import { BreezeBridgeAngularModule, AjaxAngularAdapter } from 'breeze-bridge-angular';

let breeze_client = require('breeze-client');
require('breeze-client-labs/breeze.ajaxpost');

@NgModule({
    declarations: [],
    imports: [HttpModule],
    providers: []
})
export class BreezeBridgeModule {
    constructor(private http: Http) {
         breeze_client.config.registerAdapter('ajax', () => new AjaxAngularAdapter(http));
        let ajax = breeze_client.config.initializeAdapterInstance('ajax', AjaxAngularAdapter.adapterName, true);
        breeze_client.ajaxpost(ajax); // now we can use POST
    }
}`

Argument of type 'Http' is not assignable to type 'Http'  Property _'backend' is protected but type 'Http' is not a class derived from 'Http"

if I try to cast to <any>http I still get build errors

ERROR in Error encountered resolving symbol values statically. Calling function
'makeDecorator', function calls are not supported. Consider replacing the functi
on or lambda with a reference to an exported function, resolving symbol NgModule
 in C:/VPS/Fng.Vps/Dev/Primary/Source/Fng.Vps.Portal.Web/Client/node_modules/bre
eze-bridge-angular/node_modules/@angular/core/src/metadata/ng_module.d.ts, resol
ving symbol NgModule in C:/VPS/Fng.Vps/Dev/Primary/Source/Fng.Vps.Portal.Web/Cli
ent/node_modules/breeze-bridge-angular/node_modules/@angular/core/src/metadata.d
.ts, resolving symbol NgModule in C:/VPS/Fng.Vps/Dev/Primary/Source/Fng.Vps.Port
al.Web/Client/node_modules/breeze-bridge-angular/node_modules/@angular/core/src/
core.d.ts, resolving symbol NgModule in C:/VPS/Fng.Vps/Dev/Primary/Source/Fng.Vp
s.Portal.Web/Client/node_modules/breeze-bridge-angular/node_modules/@angular/cor
e/index.d.ts, resolving symbol BreezeBridgeAngularModule in C:/VPS/Fng.Vps/Dev/P
rimary/Source/Fng.Vps.Portal.Web/Client/node_modules/breeze-bridge-angular/index
.d.ts, resolving symbol BreezeBridgeAngularModule in C:/VPS/Fng.Vps/Dev/Primary/
Source/Fng.Vps.Portal.Web/Client/node_modules/breeze-bridge-angular/index.d.ts

**Comment by marcelgood** [comment]
It currently only supports up to the latest stable version which is v2.4.9. v4 introduces braking changes. I will eventually update the bridge to support v4 as it gets closer to final release.

**Comment by dsoltesz** [comment]
I actually just took a copy of the file and plopped it in, works fine, no code changes were needed for the adapter.

**Comment by marcelgood** [comment]
That's good. Most likely just needs to be rebuilt against v4 to update the `index.metadata.json` file.

**Comment by badre429** [comment]
it work on angular 4 after installing breeze.bridge.angular
1. delete "dependency" on package.json on 
`<project>/node_module/breeze.bridge.angular`

2. delete the folder `<project>/node_module/breeze.bridge.angular/node_module`

> note : i am using node 6.9.5

**Comment by marcelgood** [comment]
Quick update. I just published `breeze-bridge-angular@4.0.0-alpha1`. This should work with the final version of Angular v4. Just doing some more testing and updating the TempHire sample to v4. If everything works out, I'll go ahead and publish a final version.

**Comment by dsoltesz** [comment]
Awesome, thanks
