### ISSUE TITLE
Helper for generate Angular Reactive from validation 

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze.bridge.angular#14]
Angular Reactive Form has huge flexibity we use it in our form validation 
```ts
 createForm() {
    this.userForm = this.fb.group({
      username: ['', Validators.required ],
      name: ['', Validators.required ],
      email: ''
    });
```
is it possible to generate validation information from breeze metadata

**Comment by marcelgood** [comment]
Yep, certainly possible. The information is all there. You just have to write a utility that extracts the information from the metadata store. I don't know much about Angular Reactive Form, but I'm doing something similar on a current project. We are using the DxForm from DevExpress.

The DxForm has the ability to add custom validation rules, so I just wrote a rule that interfaces with Breeze to get the validation error(s) for a given field. In this case Breeze is actually doing the validation, that way I don't have to repeat all the validation rules in the form. So the form basically has only a single validation rule for each field and Breeze is doing all the work.
