### ISSUE TITLE
How do I bind to breeze entity group so that whole collection is observed and any change to collection is reflected?

### ISSUE THREAD

**Issue by DotNetPart** [Breeze/breeze.bridge.angular#15]
I tried to explain desired behavior with my changes to temphire.angular app:
https://github.com/DotNetPart/temphire.angular/commit/992ff6d298fd6d760bda071e72c5db7da242cceb

In the main component I added the button to add new State entity and need that state to become available
in the dropdown for address editing immediately. Is there a way to achieve that having in mind that I might want such behavior for any other entity in the model?

**Comment by marcelgood** [comment]
This is something that you would accomplish using reactive style programming. I've coded up the example for the states array. Notice that you need to add the new state to the correct unit of work instance. I moved your test button down to the contacts component, so the factory operates against the unit of work instance that we are bound to. The resource-mgt component has its own unit of work that is sandboxed from the detail components. 

https://github.com/DotNetPart/temphire.angular/commit/8be5994ee5dd864884936c6629c49f8c12eefb41

**Comment by steveschmitt** [comment]
The other option is to keep `states` as a normal array in your component, and add to it directly when you create a new state:

    addStateToList() {
        let state = <State> {
        id: 'PR',
        shortName: 'PR',
        name: "Puerto Rico",
        rowVersion: 0
    };
    let stateEntity = this.unitOfWork.stateFactory.create(state);
    this.states.push(stateEntity);  // add to states array; shows up in UI

It's simple than Marcel's approach, but it only works within that component.  Marcel's approach works even if a separate component or service calls `stateFactory.create()`.

**Comment by DotNetPart** [comment]
@marcelgood , @steveschmitt Thank you guys. This helped!

**Comment by DotNetPart** [comment]
@marcelgood @steveschmitt, sorry to continue discussion in a closed issue, but imagine I have Users and Orders connected. So, User entity has orders: Order[].
