### ISSUE TITLE
How configure for angular final 

### ISSUE THREAD

**Issue by harilalinapp** [Breeze/breeze.bridge.angular#5]
I tried to implement the breezejs for odata i angular2 final. I can't set the service name. Also needs to add header authorization . Is there any documentation or example to use?

**Comment by marcelgood** [comment]
Why can't you set the service name? The TempHire example is a comprehensive example. It's not using odata, but which data service adapter you use doesn't change how you set the service name. 

https://github.com/Breeze/temphire.angular2/blob/master/TempHire/app/core/services/entity-manager-provider.ts

It sets the service name on line 30.

The authorization header question was discussed earlier in another issue. You should find all the information that you need here:

https://github.com/Breeze/breeze.bridge.angular2/issues/2

**Comment by harilalinapp** [comment]
@marcelgood Thanks for the reply. But i couldn't understand the flow. Actually am new to angular2 also. IS it possible to get any doc or something on how it's works?

**Comment by marcelgood** [comment]
I understand it's daunting to learn new things. We all had to learn Angular 2 first. Documentation on Angular 2 can be found at https://angular.io/, which you probably already know. How to use Breeze and how it works is all documented on our site http://breeze.github.io/doc-js/. Most of that is independent of whether you use Angular 2 or another framework. The specifics for how to use the Breeze Angular 2 bridge are documented here in this repo's README file and TempHire is the most thorough example that we currently have that demonstrates it all in action. We don't currently have a simple tutorial for building an Angular 2 app with Breeze. There are other smaller examples on the getbreezenow.com website that demonstrate some of the fundamental aspects of Breeze. All of that carries over. 

We as a company consult on this stuff, so if you are interested in getting some help, you can contact us at https://www.ideablade.com/services.

There are some independent folks that are starting to do presentations and courses on this subject. For example Brian Noyes presented an introduction to Breeze with Angular 2 today at VS Live. I think they'll post the video recording. https://vslive.com/Events/Anaheim-2016/Sessions/Thursday/TH01-Building-DataCentric-Apps-with-Angular-2-and-Breeze.aspx

So, there is a lot of information out there and a pretty decent community on http://stackoverflow.com/questions/tagged/breeze as well who'll answer questions on Breeze etc.

**Comment by harilalinapp** [comment]
I will check it. Meantime the current app is build to connect to webapi, right?. How it's possible to change to odata? Something like Northwind ?

**Comment by marcelgood** [comment]
Yes, the current app is configured to connect to a .NET WebApi backend, as well as to a Node.js Sequelize backend. More information on how to configure Breeze to connect to an OData backend can be found here:

http://breeze.github.io/doc-js/server-odata.html

There's also some information here about considerations with Angular 2. The above documentation doesn't talk about how to import datajs as a module, but I explained it in this SO post.

http://stackoverflow.com/questions/39352922/breezejs-angular-2-and-odata
